/* Main.c file generated by New Project wizard
 *
 * Created:   3.17
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
#include<intrins.h> 
#define uchar unsigned char
#define uint unsigned int
xdata unsigned char CLCK _at_ 0x9000;   
xdata unsigned char CHCK _at_ 0x9001;   
xdata unsigned char RLCK _at_ 0x9002;  
xdata unsigned char RHCK _at_ 0x9003;  
uchar code Table_C[]=
{//clck chck
   0xff,0xfe,
   0xff,0xfd,
   0xff,0xfb,
   0xff,0xf7,
   0xff,0xef,
   0xff,0xdf,
   0xff,0xbf,
   0xff,0x7f,
   0xfe,0xff,
   0xfd,0xff,
   0xfb,0xff,
   0xf7,0xff,
   0xef,0xff,
   0xdf,0xff,
   0xbf,0xff,
   0x7f,0xff
};
uchar code Table_Smile[]=
{
0x00,0x00,0x3F,0xFC,0x40,0x02,0x80,0x01,0x83,0xC1,0x84,0x21,0x88,0x11,0x80,0x01,
0x80,0x01,0x98,0x19,0xA4,0x25,0x98,0x19,0x80,0x01,0x40,0x02,0x3F,0xFC,0x00,0x00
};
uchar code Table_Cry[]=
{
0x00,0x00,0x3F,0xFC,0x40,0x02,0x80,0x01,0x88,0x11,0x84,0x21,0x83,0xC1,0x80,0x01,
0x80,0x01,0x98,0x19,0xA4,0x25,0x98,0x19,0x80,0x01,0x40,0x02,0x3F,0xFC,0x00,0x00
};
//七段译码 数码管选择
uchar code SEGCC_CODE[]={0x3f,0x06,0x5b,0x4f,0x66,0x6d,0x7d,0x07,0x7f,0x6f,0x77,0x7c,0x39,0x5e,0x79,0x71}; 
uchar code SEGLOCAL_CODE[]={0x40,0x20,0x10,0x08,0x04,0x02,0x01}; 
//选手积分
uchar score[]={0,0,0,0,0};
//选手对应的LED灯
sbit LED1=P1^0;
sbit LED2=P1^1;
sbit LED3=P1^2;
sbit LED4=P1^3;
//选手对应的抢答键
sbit player1=P1^4;
sbit player2=P1^5;
sbit player3=P1^6;
sbit player4=P1^7;
sbit beep=P3^0;
//位选wx 片选px
uchar xdata *px;
uchar xdata *wx;
//定义时间，选手号，答题状态，中断计数
uchar t,player,status,tt;
uchar ii,jj;
//ms延时 
void DelayMS(uint x) 
{  
   uchar i;
   while(x--)
      {
	 for(i=0;i<120;i++);
      }
}
//进入抢答状态
void myint0() interrupt 0 
{
	 
   if(status==1)
   {
      score[player]++;
      P1=0x00;    
      t=0;
      status=0;
      jj=30;
      *wx=0x00;
      while(jj--&&player)
      {
	 for(ii=0;ii<32;ii+=2)
	 {
	    RHCK=~Table_C[ii];
	    RLCK=~Table_C[ii+1];
	    CHCK=~Table_Smile[ii];
	    CLCK=~Table_Smile[ii+1];
	    DelayMS(2);
	 }
      }
      RLCK=0x00;
      RHCK=0x00;
      player=0;
      TR0=0;
   }
   else
   {
      t=10;
      status=1;
      TR0=1;
      tt=20;
   }    
}
//时间控制中断
void mytime0() interrupt 1 
{
   TH0=(65536-50000)/256; 
   TL0=(65536-50000)%256; 
   tt--;
   if(tt==0)
   {
      tt=20;
      if(status==0)
      {
	 return;
      }
      else if(status==1)
      {
	 if(t==0)
	 {
	    return;
	 }
	 else
	 {
	    t--;
	 }
      }
   }
}
//显示积分中断
void myint1() interrupt 2 
{
   if(status==1)
   {
      //score[player]++;
      P1=0x00;
      
      t=0;
      status=0;
      jj=30;
      *wx=0x00;
      while(jj--&&player)
      {
	 for(ii=0;ii<32;ii+=2)
	 {
	    RHCK=~Table_C[ii];
	    RLCK=~Table_C[ii+1];
	    CHCK=~Table_Cry[ii];
	    CLCK=~Table_Cry[ii+1];
	    DelayMS(2);
	 }
      }
      RLCK=0x00;
      RHCK=0x00;
      player=0;
      TR0=0;
   }
   else if(status==2)
   {
      uchar i;
      for(i=0;i<=4;i++)
      {
	 score[i]=0;
      }
   }
   else
   {
      status=2;
   }
}
//显示选手号
void showplayer()
{
   *px=SEGLOCAL_CODE[3];
   *wx=SEGCC_CODE[player];
   DelayMS(1);
}
//显示时间
void showtime()
{
   uchar thh,tll;
   thh=t/10;
   tll=t%10;
   
   *px=SEGLOCAL_CODE[5];
   *wx=SEGCC_CODE[thh];
   DelayMS(5);
  
   *px=SEGLOCAL_CODE[6];
   *wx=SEGCC_CODE[tll];
   DelayMS(5);
   return;
}
//选手号闪烁
void shineplayer()
{
   uchar k=5;
   while(k)
   {
      *px=SEGLOCAL_CODE[3];
      *wx=SEGCC_CODE[player];
      
      DelayMS(100);
      
      *px=SEGLOCAL_CODE[3];
      *wx=0x00;
       DelayMS(100);
      k--;
   }
}
//显示积分
void showscore()
{
   *px=SEGLOCAL_CODE[1];
   *wx=SEGCC_CODE[score[1]];
   DelayMS(5);
   
   *px=SEGLOCAL_CODE[2];
   *wx=SEGCC_CODE[score[2]];
   DelayMS(5);
   
   *px=SEGLOCAL_CODE[3];
   *wx=SEGCC_CODE[score[3]];
   DelayMS(5);
   
   *px=SEGLOCAL_CODE[4];
   *wx=SEGCC_CODE[score[4]];
   DelayMS(5);
}

void main(void)
{
   uchar tmp;
   P1=0x00;//初始化LED
   status=0;
   player=0;
   t=0;
   px=0x8002;//片选地址
   wx=0x8004;//位选地址
   EX0=1;
   EX1=1;
   IT0=1;
   IT1=1;
   
   TMOD=0x21;    //计数器 T0 方式 1  T1 方式2
   ET0=1;
   tt=20;
   TH0=(65536-50000)/256; 
   TL0=(65536-50000)%256; 

   EA=1;
   
   while (1)
   {
      //判断是否有选手作答
      if(player==0)
      {
	 //判断选手是否按键
	 //P1=0XF0;
	 tmp=P1;
	 if(P1==0x00)
	 {
	    showplayer();
	    showtime(); 
	    if(status==1&&t==0)
	    {
	       status=0;
	    }
	    if(status==2)
	    {
	       uchar p;
	       p=50;
	       while(p&&status==2)
	       {
		  showscore();
		  DelayMS(5);
		  p--;
	       }
	       if(status==2)status=0;
	    }
	 }
	 else
	 {
	    if(player1==1)
	    {
	       player=1;
	    }
	    if(player2==1)
	    {
	       player=2;
	    }
	    if(player3==1)
	    {
	       player=3;
	    }
	    if(player4==1)
	    {
	       player=4;
	    }
	    switch(status)
	    {
	       case 0:
	       {
		  
		  if(player==0)
		  {}
		  else
		  { 
		     shineplayer();
		     player=0;
		     status=0;
		  }
		  break;
	       }
	       case 1:
	       {
		  if(player==0)
		  {}
		  else
		  {
		     t=30;
		     if(player==1)
			LED1=1;
		     if(player==2)
			LED2=1;
		     if(player==3)
			LED3=1;
		     if(player==4)
			LED4=1;
		  }   
	       } 
            }
	 }
      }
      else
      {
	  showplayer();
          showtime(); 
	 if(player==0)
	 {
	    continue;
	 }
	 else
	 {
	    if(t==0)
	    {
	       shineplayer();
	       player=0;
	       P1=0x00;
	    }
	 }
	 //提前结束部分
      }
     
   }
}